const prefixes: string[] = [
  "Abelia",
  "Abelmoschus",
  "Abutilon",
  "Acanthus",
  "Acca",
  "Acer",
  "Achillea",
  "Acorus",
  "Aeonium",
  "Aesculus",
  "Agapanthus",
  "Agastache",
  "Agave",
  "Ajuga",
  "Albizia",
  "Alcea",
  "Alchemilla",
  "Allium",
  "Aloe",
  "Alstroemeria",
  "Alyogyne",
  "Amorpha",
  "Amorphophallus",
  "Anaphalis",
  "Anemone",
  "Angelonia",
  "Anoda",
  "Anthriscus",
  "Antirrhinum",
  "Aquilegia",
  "Arbutus",
  "Arctostaphylos",
  "Aristolochia",
  "Armeria",
  "Artemesia",
  "Artemisia",
  "Arum",
  "Asplenium",
  "Aster",
  "Atriplex",
  "Babiana",
  "Baccharis",
  "Ballota",
  "Bambusa",
  "Beetroot",
  "Berberis",
  "Bergenia",
  "Berlandiera",
  "Beta",
  "Bouteloua",
  "Bromelia",
  "Bromeliad",
  "Buddleja",
  "Bulbine",
  "Buxus",
  "Caesalpinia",
  "Calendula",
  "Calibrachoa",
  "Callicarpa",
  "Calochortus",
  "Calycanthus",
  "Camellia",
  "Campanula",
  "Campsis",
  "Cana",
  "Canna",
  "Carex",
  "Carpenteria",
  "Caryopteris",
  "Catalpa",
  "Ceanothus",
  "Centaurea",
  "Centranthus",
  "Cephalanthus",
  "Cephalaria",
  "Cerastium",
  "Ceratostigma",
  "Ceratotheca",
  "Cercis",
  "Cereus",
  "Chaenomeles",
  "Chionochloa",
  "Chrysanthemum",
  "Chrysocephalum",
  "Cistus",
  "Citrus",
  "Cleome",
  "Clerodendrum",
  "Colchicum",
  "Colocasia",
  "Convolvulus",
  "Coprosma",
  "Coreopsis",
  "coreopsis",
  "Cornus",
  "Correa",
  "Cosmos",
  "Cotinus",
  "Cotula",
  "Crassula",
  "Crocosmia",
  "Crocus",
  "Cryptomium",
  "Cuphea",
  "Cupressus",
  "Cymbalaria",
  "Cynara",
  "Cyperus",
  "Delosperma",
  "Delphinium",
  "Deschampsia",
  "Dianthus",
  "Diascia",
  "Dicentra",
  "Dichelostemma",
  "Dicksonia",
  "Dietes",
  "Digitalis",
  "Diospyros",
  "Diplacus",
  "Dodecatheon",
  "Dolichos",
  "Dorycnium",
  "Dudleya",
  "Duranta",
  "Echeveria",
  "Echinacea",
  "Elaeocarpus",
  "Equisetum",
  "Erigeron",
  "Eriobotrya",
  "Eriogonum",
  "Erodium",
  "Erysimum",
  "Escallonia",
  "Eschscholzia",
  "Eucomis",
  "Euonymus",
  "Euphorbia",
  "Euryops",
  "Fatsia",
  "fern",
  "Festuca",
  "Ficus",
  "Foeniculum",
  "Fraxinus",
  "Freesia",
  "Fremontodendron",
  "Fritillaria",
  "Gaillardia",
  "Galtonia",
  "Gardenia",
  "Gaura",
  "Gazania",
  "Gelsemium",
  "Geranium",
  "Gerbera",
  "Geum",
  "Ginkgo",
  "Glaucium",
  "Grevillea",
  "Haloragis",
  "Hebe",
  "Hedychium",
  "Helianthemum",
  "Helianthus",
  "Helleborus",
  "Hemerocallis",
  "Heracleum",
  "Heteromeles",
  "Heuchera",
  "Hibiscus",
  "Houttuynia",
  "Hyacinthoides",
  "Hyacinthus",
  "Hybiscus",
  "Hydrangea",
  "Hypericum",
  "Ilex",
  "Imperata",
  "Ipheion",
  "Ipomoea",
  "Iris",
  "Juncus",
  "Kalanchoe",
  "Keckelia",
  "Kerria",
  "Knautia",
  "Kniphofia",
  "Lagerstroemia",
  "Lamium",
  "Lantana",
  "lathyrus",
  "Laurus",
  "Lavandula",
  "Lavatera",
  "Leonotis",
  "Lepechinia",
  "Leptinella",
  "Leucojum",
  "Libertia",
  "Ligustrum",
  "Lilium",
  "Linaria",
  "Liriope",
  "Lithodora",
  "lobelia",
  "Lonicera",
  "Lornica",
  "Loropetalum",
  "Lupinus",
  "Lychnis",
  "Lycianthes",
  "Lysimachia",
  "Magnolia",
  "Mahonia",
  "Malva",
  "Melia",
  "Melianthus",
  "Mimulus",
  "Moluccella",
  "Moraea",
  "Morus",
  "Muhlenbergia",
  "Muscari",
  "Myrtus",
  "Nandina",
  "Narcissus",
  "narcissus",
  "Nassella",
  "nectaroscordum",
  "Nepeta",
  "Nerium",
  "Nicotiana",
  "Nierembergia",
  "Nigella",
  "Nymphaea",
  "Oenothera",
  "Olea",
  "Origanum",
  "Osteospermum",
  "Oxalis",
  "Papaver",
  "Parahebe",
  "Paulownia",
  "Pavonia",
  "Pedicularis",
  "Pelargonium",
  "Pennisetum",
  "Penstemon",
  "Pentagramma",
  "Peony",
  "Perovskia",
  "Petroselinum",
  "Petunia",
  "Phlomis",
  "Phlox",
  "Phormium",
  "Photinia",
  "Phygelius",
  "Physocarpus",
  "Physostegia",
  "Phytolacca",
  "Pittosporum",
  "Platycodon",
  "Primula",
  "Prunus",
  "Pseudosasa",
  "Punica",
  "Pyracantha",
  "Pyrus",
  "Quercus",
  "Rhamnus",
  "Rhaphiolepis",
  "Rhododendron",
  "Rhus",
  "Ribes",
  "Ricinus",
  "Rosa",
  "Rosmarinus",
  "Rudbeckia",
  "Ruellia",
  "Rumex",
  "Salix",
  "salix",
  "Salvia",
  "Santolina",
  "Sasaella",
  "Scabiosa",
  "Scilla",
  "Scutellaria",
  "Sedum",
  "Sempervivum",
  "Senecio",
  "Sesbania",
  "Silene",
  "Sisyrinchium",
  "Solanum",
  "Solidago",
  "Spiraea",
  "Stachys",
  "Stipa",
  "Strelitzia",
  "Supertunia",
  "Symphoricarpos",
  "Symphytum",
  "Syringa",
  "Tanacetum",
  "Tetrapanax",
  "Teucrium",
  "Thymus",
  "Tithonia",
  "Trachelium",
  "Trachelospermum",
  "Tradescantia",
  "Trichostema",
  "Tropaeoleum",
  "Tulbaghia",
  "Tulipa",
  "Umbellularia",
  "Verbascum",
  "verbascum",
  "Verbena",
  "Veronica",
  "Viburnum",
  "Viola",
  "Vitex",
  "Vitis",
  "Wahlenbergia",
  "Wisteria",
  "Yucca",
  "Zauschneria",
  "Zinnia",
]
const suffixes: string[] = [
  "grandiflora",
  "x grandiflora 'Edward Goucher'",
  "manihot",
  "pictum",
  "mollis",
  "sellowiana",
  "negundo californicum",
  "palmatum",
  "palmatum 'Burgundy Lace',",
  "palmatum dissectum",
  "palmatum dissectum atropurpureum 'Garnet'",
  "millefolium",
  "ptarmica ‘The Pearl Superior’",
  "gramineus 'Ogon'",
  "arboreum atropurpureum 'Zwartkop'",
  "californica",
  "'Apricot Sunrise'",
  "Americana",
  "Americana 'variegata'",
  "ocahui",
  "genevensis",
  "reptans 'Burgundy Glow'",
  "reptans 'Catlin's Giant'",
  "julibrissin",
  "julibrissin 'Summer chocolate'",
  "rosea",
  "rosea 'Black Beauty'",
  "'Purple sensation'",
  "subhirsutum",
  "castanea",
  "‘Johnson’s Hybrid’",
  "huegelii",
  "margaritacea",
  "coronaria",
  "japonica",
  "angustifolia",
  "cristata",
  "sylvestris 'Raven's Wing'",
  "'Black Prince'",
  "'Ruby Port'",
  "caerulea 'Crimson Star'",
  "caerulea 'Kristal'",
  "flavescens",
  "formosa",
  "fragrans",
  "viridiflora 'Chocolate Soldier'",
  "vulgaris 'Black Beauty'",
  "unedo",
  "unedo compacta",
  "densiflora 'Howard Mcminn'",
  "edmundsii 'Carmel Sur'",
  "uva-ursi",
  "viscida",
  "maritima",
  "alba 'Canescens'",
  "'Powis castle'",
  "abrotanum 'Tangerine'",
  "douglasiana",
  "ludoviciana 'Silver King'",
  "italicum",
  "cordifolius",
  "dumosus 'Sapphire'",
  "novae-angliae 'Purple Dome'",
  "occidentalis",
  "lentiformis",
  "curbiscapa",
  "pilularis",
  "viminea",
  "pseudodictamnus 'All Hallows Green'",
  "multiplex Alphonse Karr'",
  "'Bull's blood'",
  "thunbergii ‘Atropurpurea Crimson Pygmy’",
  "thunbergii “Monlers”",
  "ciliata",
  "lyrata",
  "vulgaris",
  "gracilis",
  "hybrid",
  "davidii",
  "x weyeriana 'Honeycomb'",
  "frutescens",
  "microphylla japonica",
  "sempervirens",
  "gilliesii",
  "officinalis",
  "'Million Bells'",
  "bodinieri 'Profusion'",
  "luteus",
  "garganica",
  "radicans",
  "x generalis 'Optical Sunrise'",
  "'Warscewiczii'",
  "x generalis 'Paprika'",
  "x generalis 'Wyoming'",
  "buchananii 'Red Fox'",
  "comans 'Bronze'",
  "flagellifera",
  "testacea",
  "clandonensis 'Longwood Blue'",
  "clandonensis 'Worcester Gold'",
  "x erubescens 'Purpurea'",
  "'Frosty blue'",
  "'Ray Hartman'",
  "lemmonii",
  "thyrsiflorus 'Skylark'",
  "thyrsifolia x americana 'Tuxedo'",
  "montana",
  "alba",
  "gigantea",
  "tomentosum",
  "plumbaginoides",
  "triloba",
  "canadensis",
  "peruvianus monstrose 'Rojo'",
  "speciosa",
  "rubra",
  "'Hillside Sheffield Pink’",
  "pacificum",
  "parthenium",
  "parthenium 'Aureum'",
  "ptarmiciflorum",
  "superbum 'Esther Read'",
  "apiculatum",
  "'Sunset'",
  "aguilari “Blanche”",
  "skanbergi",
  "orange",
  "hassleriana",
  "bungei",
  "trichotomum",
  "autumnale",
  "esculenta",
  "cneorum",
  "'Roy's Red'",
  "verticillata",
  "kousa",
  "pulchella 'Alba'",
  "bipinnatus 'Sonata Dwarf Ladybird Mix'",
  "bipinnatus 'Sonata'",
  "coggygria",
  "hispida 'Silver Mound'",
  "ovata",
  "'Lucifer'",
  "ignea",
  "muralis",
  "cardunculus",
  "scolymus",
  "involucratus",
  "ajacis",
  "caespitosa 'Northern Light'",
  "'Amazon Rose Magic'",
  "'Dynasty Rose Lace'",
  "'Inchmery'",
  "barbatus 'Amazon Neon Purple'",
  "barbatus nigricans",
  "caryophyllus 'Can Can Scarlet'",
  "chinensis 'Crimson Charm'",
  "superbus",
  "integerrima",
  "integerrima 'Wink Pink'",
  "multiflorum",
  "antarctica",
  "ferruginea 'Gigantea Rusty Foxglove'",
  "parviflora",
  "purpurea 'Snow Thimble'",
  "purpurea 'Dedalera'",
  "kaki",
  "puniceus",
  "Hendersonii",
  "lablab",
  "hirsutum",
  "farinosa",
  "erecta 'Sapphire Showers'",
  "purpurea",
  "decipiens",
  "hyemale",
  "karvinskianus",
  "latifolium",
  "umbellatum",
  "pelargoniflorum 'Sweethart'",
  "texanum",
  "linifolium 'Variegatum'",
  "x allionii",
  "matsuda's compacta",
  "autumnalis",
  "japonica 'Microphylla'",
  "microphylla variegata",
  "'Blackbird'",
  "'Diamond Frost'",
  "'Tasmanian Tiger'",
  "characias",
  "characius 'Portugese Velvet'",
  "cyparissas 'Fensruby'",
  "polychroma",
  "rigida",
  "seedling",
  "pectinatus",
  "idahoensis 'Siskiyou Blue'",
  "carica",
  "vulgare",
  "vulgare 'Purpurea'",
  "latifolia",
  "californicum",
  "imperialis 'Red'",
  "'Grandiflora Burgundy'",
  "regalis",
  "augusta",
  "jasminoides 'August Beauty'",
  "lindheimeri 'Corrie's Gold'",
  "sempervirens ()",
  "cantabrigiense 'Biokovo'",
  "macrorrhizum",
  "magnificum 'Johnson's Blue'",
  "pyrenaicum 'Bill Wallis'",
  "sanguineum 'Vision Light Pink'",
  "sanguineum 'Vision Purple'",
  "jamesonii",
  "coccineum 'Mango Lassi'",
  "biloba",
  "flavum aurantiacum",
  "juniperina Molonglo",
  "“Wellington Bronze”",
  "coronarium",
  "nummularium 'Dazzler'",
  "annuus 'Velvet Queen'",
  "maximilianii",
  "tuberosus",
  "foetidus",
  "orientalis",
  "'Stella d'Oro'",
  "lanatum",
  "arbutifolia",
  "micrantha",
  "micrantha 'Caramel'",
  "micrantha var. diversifolia 'Palace Purple'",
  "eetveldeanus 'Red Shield'",
  "lasiocarpus",
  "moscheutos 'Luna White Swirl'",
  "rosa-sinensis",
  "syriacus",
  "syriacus 'Red Heart'",
  "cordata",
  "cordata “Chameleon”",
  "non-scripta hybrid",
  "mochuto 'red'",
  "macrophylla",
  "macrophylla variegata",
  "quercifolia",
  "calycinum",
  "aquifolium 'Variegata'",
  "C. Rubra 'Red Baron'",
  "uniflorum",
  "batatas",
  "ensata 'Henry's White'",
  "germanica",
  "germanica 'Batik'",
  "germanica 'Exotic Isle'",
  "germanica 'Firebreather'",
  "germanica 'Fringe Benefit'",
  "germanica 'Spartan'",
  "germanica 'Spiced Custard'",
  "germanica 'Superstition'",
  "Germanica 'Supreme Sultan'",
  "germanica spec.",
  "Germanica “Unforgettable Fire”",
  "pallida 'Albo Variegata'",
  "pseudacorus",
  "reticulata 'Purple Gem'",
  "versicolor",
  "x hollandica 'White Perfection'",
  "patens 'Carman's Gray'",
  "beharensis",
  "cordifolia",
  "japonica 'Pleniflora'",
  "macedonica",
  "citrina",
  "uvaria",
  "uvaria 'Little Maid'",
  "maculatum 'Pink Chablis'",
  "camara",
  "montevidensis",
  "odoratus",
  "nobilis 'Saratoga'",
  "'Goodwin Greek Grey'",
  "angustifolia 'Alba'",
  "angustifolia 'Munstead'",
  "intermedia 'Du Provence'",
  "intermedia 'Fred Boutin'",
  "intermedia 'Grosso'",
  "spicca 'Rosea'",
  "stoechas",
  "X intermedia 'Alba'",
  "x clementii 'Barnsley'",
  "leonurus",
  "calyucina 'Rocky Point'",
  "squalida 'Platt's Black'",
  "aestivum",
  "japonicum 'Texanum'",
  "tigrinum",
  "purpurea 'Alba'",
  "muscari",
  "muscari 'Silvery Sunproof'",
  "diffusa 'Grace Ward'",
  "erinus",
  "fragrantissima",
  "ciliosa",
  "chinense 'Purple Majesty'",
  "albifrons",
  "chalcedonica",
  "coronaria 'Atrosanguinea'",
  "rantonnetii",
  "congestiflora 'Walkabout Sunset'",
  "grandiflora 'Little Gem'",
  "liliiflora 'Nigra'",
  "aquifolium",
  "arborea 'Variegata'",
  "azedarach",
  "major",
  "cardinalis",
  "lamiaceae",
  "huttonii",
  "rigens",
  "armeniacum",
  "aucheri",
  "communis",
  "domestica",
  "'Hillstar'",
  "'Paper White'",
  "'Tête à Tête",
  "'Trepolo'",
  "'Yellow Cheerfulness",
  "bulbocodium 'Golden Bells'",
  "Cyclamineus 'Jenny'",
  "Cyclamineus 'Jetfire'",
  "Double 'Obdam'",
  "double 'Orangery'",
  "double 'Pencrebar'",
  "Double 'Rosy Cloud'",
  "Double 'Tahiti'",
  "Double hybrid",
  "jonquilla 'Baby Moon'",
  "Large Cup",
  "Large Cup 'Easter Bonnet'",
  "split cup ' Love Call'",
  "split cup 'Apricot Whirl'",
  "split cup 'Broadway Star'",
  "Tazetta",
  "tazetta papyraceus",
  "tenuissima",
  "siculum",
  "subsessilis",
  "oleander",
  "'Langsdorfii'",
  "alata 'Crimson Bedder'",
  "langsdorffii 'Hot Chocolate'",
  "x sanderae 'Lime Green'",
  "caerulea 'Purple Robe'",
  "europaea",
  "laevigatum 'Hopley's Purple'",
  "vulgare 'Variegata'",
  "deppei 'Iron Cross'",
  "triangularis",
  "atlanticum 'Flore Pleno'",
  "perfoliata",
  "tomentosa",
  "hastata",
  "densiflora",
  "different spec.",
  "alopecuroides",
  "alopecuroides 'Mody'",
  "setaceum 'Rubrum'",
  "'Husker Red Strain'",
  "'Madera'",
  "Heterophyllus",
  "mexicali 'Pikes Peak Purple'",
  "pinifolius 'Mersea Yellow'",
  "sp .",
  "atriplicifolia",
  "neapolitanum",
  "'Wave Rose'",
  "fruticosa",
  "lanata",
  "russeliana",
  "paniculata 'David'",
  "paniculata 'Ruby mine'",
  "subulata",
  "tenax 'Amazing Red'",
  "tenax 'Rubrum'",
  "x rectus 'African Queen',",
  "x rectus 'Moonraker'",
  "capitatus",
  "opulifolius 'Coppertina'",
  "'Vivid'",
  "americana",
  "tobira",
  "tobira 'Variegata'",
  "grandiflorus 'Fuji White'",
  "auricula 'Abuelita'",
  "polianthus spec",
  "polyantha 'Victoriana Silver Lace'",
  "cerasifera 'Purple Pony'",
  "persica 'Galaxy'",
  "virginiana",
  "owatarii",
  "granatum",
  "granatum 'Nana'",
  "pyrifolia",
  "douglassii",
  "kelloggii",
  "wislizenii",
  "alaternus",
  "crocea",
  "indica 'Jack Evans'",
  "umbellata 'Minor'",
  "integrifolia",
  "typhina",
  "typhina 'Bailtiger'",
  "aureum",
  "communis 'Carmencita'",
  "'Flutterbye'",
  "'Santana'",
  "banksiae 'Lutea'",
  "chinensis 'Mutabilis'",
  "cultv. 'The Shepherdess'",
  "culv.'The dark lady'",
  "Floribunda 'Angel Face'",
  "floribunda 'Cherish'",
  "floribunda 'Cinco de Mayo'",
  "floribunda 'Disneyland'",
  "floribunda 'Europeana'",
  "Floribunda 'Lime Sublime'",
  "Grandiflora 'Honey Dijon'",
  "grandiflora 'Tournament of Roses'",
  "hybrid 'Glamis Castle'",
  "hybrid 'Fair Bianca'",
  "hybrid 'Gizmo'",
  "hybrid 'Graham Thomas'",
  "hybrid 'Gypsy Dancer'",
  "hybrid 'Iceberg'",
  "hybrid 'Moondance'",
  "hybrid 'Pat Austin'",
  "hybrid 'Peak Performance'",
  "hybrid 'Sixteen Candles'",
  "hybrid 'Strike It Rich'",
  "hybrid 'Wild Spice'",
  "hybrid musk 'Ballerina'",
  "hybrid tea 'Brandy'",
  "miniature hybrid",
  "Polyantha 'Lovely Fairy'",
  "tea hybrid 'Orange Surprise'",
  "officinalis 'Huntington Carpet'",
  "hirta 'Cherokee Sunset'",
  "hirta 'Prairie Sun'",
  "brittoniana",
  "sanguineus 'Sanguineus'",
  "babylonica 'Tortuosa'",
  "lucida ssp. lasiandra",
  "'Bee's Bliss'",
  "'Mystic Blue Spires'",
  "apiana",
  "argentea",
  "azurea grandiflora",
  "chamaedryoides",
  "Clevelandii 'Allen Chickering'",
  "coccinea",
  "corrugata",
  "elegans",
  "farinacea",
  "forskaohlei",
  "greggii",
  "greggii 'Limelight'",
  "greggii 'Navajo Rose'",
  "greggii 'Teresa'",
  "gregii 'White'",
  "horminum (viridus)",
  "involucrata",
  "leucantha",
  "leucophylla",
  "microphylla",
  "microphylla 'San Carlos Festival'",
  "nubicola",
  "officinalis 'Purpurea'",
  "officinalis ‘Tricolor’",
  "patens 'Cambridge Blue'",
  "sclarea",
  "sonomensis",
  "spathacea",
  "splendens 'Phoenix bright Lilac'",
  "superba 'Dark Queen Violet",
  "superba 'Rose Queen'",
  "uliginosa",
  "verticillata 'Purple Rain'",
  "viridis",
  "chamaecyparissus",
  "rosmarinifolia",
  "masamuneana “Albostrlata”",
  "atropurpurea",
  "atropurpurea 'Florist's Blue'",
  "caucasica 'Butterfly Blue'",
  "caucasica 'Perfecta Alba'",
  "ochroleuca",
  "peruviana",
  "siberica",
  "hispanicum",
  "hylotelephium 'Lynda Windsor'",
  "kamtschaticum",
  "kamtschaticum 'variegatum'",
  "lineare 'Variegatum'",
  "makinoi 'Ogon'",
  "reflexum",
  "rupestre 'Angelina'",
  "spurium 'Dragon's Blood'",
  "telephium 'Autumn Joy'",
  "tectorum",
  "cristobalensis",
  "punicea",
  "'Rolly's Favorite'",
  "dioica 'Clifford Moor' (Catchfly)",
  "uniflora",
  "uniflora 'Druett’s variegata'",
  "bellum",
  "striatum",
  "laciniatum",
  "pseudocapsicum",
  "rugosa ‘Fireworks’",
  "douglasii",
  "byzantina",
  "nicolai",
  "reginae",
  "'Pretty Much Picasso'",
  "albus",
  "officinale",
  "papyrifer",
  "chamaedrys",
  "fruticans",
  "fruticans 'Azureum'",
  "marum",
  "praecox 'Elfin'",
  "pseudolanuginosus",
  "vulgaris 'Argenteus'",
  "rotundifolia",
  "caeruleum 'Jemmy Royal Purple'",
  "jasminoides",
  "'Purple Sabre'",
  "pallida",
  "minus 'Black Velvet'",
  "violacea",
  "'Black Hero'",
  "'Lilyfire'",
  "'Top parrot'",
  "chaixii 'Album'",
  "phoeniceum",
  "phoeniceum 'Violetta'",
  "thapsus",
  "bonariensis",
  "lasiostachys",
  "rigida 'Polaris'",
  "longifolia",
  "peduncularis 'Georgia Blue'",
  "suspensum",
  "tinus",
  "odorata",
  "agnus-castus",
  "agnus-castus 'Cooke's Purple'",
  "vinifera",
  "vinifera 'Ruby Seedless'",
  "vinifera 'Thompson Seedless'",
  "vinifera 'Tokay'",
  "cuspidata",
  "sinensis x floribunda 'Rosea'",
  "filamentosa 'Bright Edge'",
  "gloriosa",
  "gloriosa 'variegata'",
  "recurvifolia",
  "(Epilobium) californica",
  "profusion",
]

export default function randomPlantName(): string {
  const prefix = prefixes[Math.floor(Math.random() * prefixes.length)]
  const suffix = suffixes[Math.floor(Math.random() * suffixes.length)]
  return `${prefix} ${suffix}`
}
