packages:
  - apps/*
  - packages/*

catalog:
  eslint: ^9.38.0
  expo: ~54.0.13
  jazz-tools: ~0.18.27

linkWorkspacePackages: true

patchedDependencies:
  '@bam.tech/react-native-image-resizer': patches/@bam.tech__react-native-image-resizer.patch

preferWorkspacePackages: true
