packages:
  - apps/*
  - packages/*

catalog:
  expo: 54.0.13
  jazz-tools: ^0.18.25
  eslint: ^9.37.0

linkWorkspacePackages: true
preferWorkspacePackages: true

patchedDependencies:
  "@bam.tech/react-native-image-resizer": patches/@bam.tech__react-native-image-resizer.patch
