name: Create Production Builds

on:
  push:
    branches: ["production"]

jobs:
  fingerprint:
    name: Calculate Fingerprint
    type: fingerprint
    environment: production
  get_ios_build:
    name: Check for existing iOS build
    type: get-build
    needs: [fingerprint]
    params:
      platform: ios
      profile: production
      distribution: store
      channel: production
  build_ios:
    name: Build iOS
    type: build
    needs: [get_ios_build]
    if: ${{ !needs.get_ios_build.outputs.build_id }}
    params:
      platform: ios
      profile: production
  submit_ios_build:
    name: Submit iOS build
    type: submit
    needs: [build_ios]
    params:
      build_id: ${{ needs.build_ios.outputs.build_id }}
  publish_ios_update:
    name: Publish iOS update
    type: update
    needs: [get_ios_build]
    if: ${{ needs.get_ios_build.outputs.build_id }}
    params:
      branch: production
      platform: ios
